argus.animations.blocks=true
argus.animations.enabled=true
argus.animations.fire=true
argus.animations.lava=true
argus.animations.portal=true
argus.animations.sculk_sensor=true
argus.animations.water=true
argus.better_grass.crimson_nylium=true
argus.better_grass.dirt_path=true
argus.better_grass.farmland=true
argus.better_grass.grass_block=true
argus.better_grass.ignore_resource_pack=false
argus.better_grass.mode=fancy
argus.better_grass.mycelium=true
argus.better_grass.podzol=true
argus.better_grass.snowy_grass_block=true
argus.better_grass.warped_nylium=true
argus.better_snow.enabled=true
argus.cit.enabled=true
argus.colors.biome.enabled=true
argus.colors.sky.enabled=true
argus.ctm.debug_logging=false
argus.ctm.enabled=true
argus.custom_animations.enabled=true
argus.custom_animations.mipmap_distance=4
argus.custom_colors.enabled=true
argus.custom_entity_models.enabled=true
argus.custom_gui.enabled=true
argus.custom_sky.enabled=true
argus.details.cloud_height=192
argus.details.clouds.enabled=true
argus.details.moon.enabled=true
argus.details.rain_snow.enabled=true
argus.details.sky.enabled=true
argus.details.stars.enabled=true
argus.details.sun.enabled=true
argus.details.vignette.enabled=true
argus.enabled=false
argus.entities.beacon_beam=true
argus.entities.enchanting_table_book=true
argus.entities.item_frames=true
argus.entities.limit_beacon_beam_height=false
argus.entities.name_tags.enabled=true
argus.entities.paintings=true
argus.entities.piston_animations=true
argus.entities.player_name_tags=true
argus.entities.shadows.enabled=true
argus.entity_textures.debug=false
argus.entity_textures.emissive_block_entities=true
argus.entity_textures.emissive_entities=true
argus.entity_textures.enabled=true
argus.entity_textures.random_block_entities=true
argus.entity_textures.random_entities=true
argus.extras.fullscreen_mode=windowed
argus.extras.instant_sneak=false
argus.fog.air=true
argus.fog.enabled=true
argus.fog.lava=true
argus.fog.powder_snow=true
argus.fog.water=true
argus.general.duplicate_translucent_backfaces=true
argus.hud.coords=false
argus.hud.corner=bottom_right
argus.hud.fps=false
argus.hud.fps_extended=false
argus.hud.steady_debug=false
argus.hud.steady_debug_refresh_interval=10
argus.hud.text_contrast=shadow
argus.natural_textures.enabled=true
argus.particles.block_break=true
argus.particles.block_breaking=true
argus.particles.dripping=true
argus.particles.enabled=true
argus.particles.explosion=true
argus.particles.firework=true
argus.particles.flame=true
argus.particles.portal=true
argus.particles.potion=true
argus.particles.rain_splash=true
argus.particles.redstone=true
argus.particles.smoke=true
argus.particles.water=true
argus.random_entities.enabled=true
argus.safe_mode=false
argus.toasts.advancement=true
argus.toasts.recipe=true
argus.toasts.system=true
argus.toasts.tutorial=true
argus.verify_mode=false
